"""routes.nmfc_data — expanded NMFC commodity code reference.

Merged with server.GENERIC_NMFC_CODES at the /nmfc/codes endpoint.
Note: the licensed NMFTA ClassIT database is proprietary; this is a
comprehensive broker reference of the most-used codes (2025 density-based
rules reflected in class guidance).
"""

EXPANDED_NMFC_CODES = [
    # Building materials
    {"nmfc": "36870", "description": "Lumber, dressed, bundled", "freight_class": "55", "category": "Building Materials"},
    {"nmfc": "36880", "description": "Plywood / OSB sheets, palletized", "freight_class": "55", "category": "Building Materials"},
    {"nmfc": "32570", "description": "Cement / concrete mix, bagged", "freight_class": "55", "category": "Building Materials"},
    {"nmfc": "35880", "description": "Drywall / gypsum board", "freight_class": "55", "category": "Building Materials"},
    {"nmfc": "26280", "description": "Bricks, blocks, pavers, palletized", "freight_class": "50", "category": "Building Materials"},
    {"nmfc": "108900", "description": "Insulation, fiberglass batts", "freight_class": "300", "category": "Building Materials"},
    {"nmfc": "150350", "description": "Pipe, PVC, bundled", "freight_class": "70", "category": "Building Materials"},
    {"nmfc": "150390", "description": "Pipe or tube, steel", "freight_class": "50", "category": "Building Materials"},
    {"nmfc": "190180", "description": "Roofing shingles, palletized", "freight_class": "55", "category": "Building Materials"},
    {"nmfc": "37860", "description": "Doors, wood or metal, crated", "freight_class": "100", "category": "Building Materials"},
    {"nmfc": "196600", "description": "Windows, glazed, crated", "freight_class": "125", "category": "Building Materials"},
    {"nmfc": "34480", "description": "Cabinets, kitchen/bath, set up", "freight_class": "125", "category": "Building Materials"},
    {"nmfc": "97120", "description": "Flooring, hardwood/laminate, cartons", "freight_class": "70", "category": "Building Materials"},
    {"nmfc": "86960", "description": "Glass, flat sheets, crated", "freight_class": "70", "category": "Building Materials"},
    # Machinery & industrial
    {"nmfc": "133300", "description": "Machinery, NOI, skidded", "freight_class": "85", "category": "Machinery & Industrial"},
    {"nmfc": "118940", "description": "Engines, internal combustion, crated", "freight_class": "85", "category": "Machinery & Industrial"},
    {"nmfc": "133110", "description": "Pumps, power, skidded", "freight_class": "85", "category": "Machinery & Industrial"},
    {"nmfc": "133120", "description": "Compressors, air, skidded", "freight_class": "85", "category": "Machinery & Industrial"},
    {"nmfc": "132620", "description": "Generators / gen-sets, skidded", "freight_class": "85", "category": "Machinery & Industrial"},
    {"nmfc": "124860", "description": "Bearings, in cartons", "freight_class": "70", "category": "Machinery & Industrial"},
    {"nmfc": "128500", "description": "Tools, hand or power, cartons", "freight_class": "85", "category": "Machinery & Industrial"},
    {"nmfc": "104200", "description": "Hose, rubber or plastic, coiled", "freight_class": "100", "category": "Machinery & Industrial"},
    {"nmfc": "106040", "description": "Chain, steel, drums or reels", "freight_class": "50", "category": "Machinery & Industrial"},
    {"nmfc": "197640", "description": "Wire, steel, coiled", "freight_class": "55", "category": "Machinery & Industrial"},
    {"nmfc": "51200", "description": "Castings, iron or steel, NOI", "freight_class": "60", "category": "Machinery & Industrial"},
    {"nmfc": "169080", "description": "Springs, steel", "freight_class": "70", "category": "Machinery & Industrial"},
    {"nmfc": "132000", "description": "Motors, electric, crated", "freight_class": "77.5", "category": "Machinery & Industrial"},
    {"nmfc": "190220", "description": "Robotics / automation equipment, crated", "freight_class": "92.5", "category": "Machinery & Industrial"},
    # Automotive
    {"nmfc": "18260", "description": "Auto parts, NOI, in cartons", "freight_class": "85", "category": "Automotive"},
    {"nmfc": "19240", "description": "Batteries, automotive, palletized", "freight_class": "60", "category": "Automotive"},
    {"nmfc": "180860", "description": "Tires, passenger/light truck", "freight_class": "70", "category": "Automotive"},
    {"nmfc": "180880", "description": "Tires, truck or off-road", "freight_class": "60", "category": "Automotive"},
    {"nmfc": "18700", "description": "Bumpers / body panels", "freight_class": "150", "category": "Automotive"},
    {"nmfc": "19940", "description": "Transmissions / transaxles, skidded", "freight_class": "85", "category": "Automotive"},
    {"nmfc": "120790", "description": "Mufflers / exhaust systems", "freight_class": "175", "category": "Automotive"},
    {"nmfc": "19325", "description": "Brake parts, cartons", "freight_class": "77.5", "category": "Automotive"},
    # Electronics & appliances
    {"nmfc": "61700", "description": "Computers / servers / laptops, cartons", "freight_class": "92.5", "category": "Electronics"},
    {"nmfc": "61990", "description": "Consumer electronics, NOI", "freight_class": "125", "category": "Electronics"},
    {"nmfc": "63940", "description": "Televisions / monitors, cartons", "freight_class": "125", "category": "Electronics"},
    {"nmfc": "116030", "description": "Telecom equipment / network gear", "freight_class": "100", "category": "Electronics"},
    {"nmfc": "60000", "description": "Electrical panels / switchgear, crated", "freight_class": "85", "category": "Electronics"},
    {"nmfc": "62700", "description": "Wire & cable, electrical, reels", "freight_class": "77.5", "category": "Electronics"},
    {"nmfc": "12480", "description": "Appliances, major (washer/dryer/range)", "freight_class": "92.5", "category": "Electronics"},
    {"nmfc": "12520", "description": "Refrigerators / freezers", "freight_class": "92.5", "category": "Electronics"},
    {"nmfc": "121500", "description": "Microwaves / small appliances, cartons", "freight_class": "125", "category": "Electronics"},
    {"nmfc": "126460", "description": "Solar panels, crated", "freight_class": "100", "category": "Electronics"},
    # Furniture
    {"nmfc": "82310", "description": "Furniture, upholstered, wrapped", "freight_class": "150", "category": "Furniture"},
    {"nmfc": "80680", "description": "Furniture, KD flat-packed, cartons", "freight_class": "100", "category": "Furniture"},
    {"nmfc": "82900", "description": "Mattresses / box springs", "freight_class": "175", "category": "Furniture"},
    {"nmfc": "81500", "description": "Office furniture, set up", "freight_class": "125", "category": "Furniture"},
    {"nmfc": "80300", "description": "Chairs, folding/stacking, cartons", "freight_class": "100", "category": "Furniture"},
    {"nmfc": "82550", "description": "Outdoor / patio furniture", "freight_class": "150", "category": "Furniture"},
    # Paper, plastics & packaging
    {"nmfc": "149980", "description": "Paper, printing, rolls or skids", "freight_class": "55", "category": "Paper & Packaging"},
    {"nmfc": "29250", "description": "Corrugated boxes, KD, bundled", "freight_class": "55", "category": "Paper & Packaging"},
    {"nmfc": "156600", "description": "Plastic articles, NOI, cartons", "freight_class": "92.5", "category": "Paper & Packaging"},
    {"nmfc": "156840", "description": "Plastic resin, pellets, bagged", "freight_class": "55", "category": "Paper & Packaging"},
    {"nmfc": "156880", "description": "Plastic film / shrink wrap, rolls", "freight_class": "85", "category": "Paper & Packaging"},
    {"nmfc": "150460", "description": "Plastic pipe fittings, cartons", "freight_class": "100", "category": "Paper & Packaging"},
    {"nmfc": "148080", "description": "Bags, paper or poly, baled", "freight_class": "70", "category": "Paper & Packaging"},
    {"nmfc": "42130", "description": "Cans, empty aluminum/steel, palletized", "freight_class": "92.5", "category": "Paper & Packaging"},
    {"nmfc": "86830", "description": "Bottles, glass, empty, palletized", "freight_class": "70", "category": "Paper & Packaging"},
    {"nmfc": "150200", "description": "Pallets, empty wood", "freight_class": "70", "category": "Paper & Packaging"},
    # Chemicals & ag
    {"nmfc": "44900", "description": "Chemicals, NOI, non-hazardous, drums", "freight_class": "60", "category": "Chemicals & Ag"},
    {"nmfc": "48580", "description": "Cleaning compounds, liquid, cases", "freight_class": "60", "category": "Chemicals & Ag"},
    {"nmfc": "149940", "description": "Paint / coatings, pails or cases", "freight_class": "60", "category": "Chemicals & Ag"},
    {"nmfc": "101700", "description": "Fertilizer, bagged", "freight_class": "50", "category": "Chemicals & Ag"},
    {"nmfc": "155050", "description": "Seed, agricultural, bagged", "freight_class": "50", "category": "Chemicals & Ag"},
    {"nmfc": "83420", "description": "Grain / feed, bagged", "freight_class": "50", "category": "Chemicals & Ag"},
    {"nmfc": "115940", "description": "Lubricants / motor oil, cases", "freight_class": "55", "category": "Chemicals & Ag"},
    {"nmfc": "4620", "description": "Adhesives / sealants, cases", "freight_class": "60", "category": "Chemicals & Ag"},
    {"nmfc": "190950", "description": "Salt, bagged (water softener / de-ice)", "freight_class": "50", "category": "Chemicals & Ag"},
    # Medical & pharma
    {"nmfc": "60000-M", "description": "Medical devices / instruments, cartons", "freight_class": "92.5", "category": "Medical & Pharma"},
    {"nmfc": "58050", "description": "Pharmaceuticals, NOI, cartons", "freight_class": "85", "category": "Medical & Pharma"},
    {"nmfc": "109600", "description": "Hospital furniture / beds, crated", "freight_class": "125", "category": "Medical & Pharma"},
    {"nmfc": "128700", "description": "Surgical supplies / PPE, cartons", "freight_class": "100", "category": "Medical & Pharma"},
    {"nmfc": "56070", "description": "Dental equipment, crated", "freight_class": "100", "category": "Medical & Pharma"},
    # Retail & consumer
    {"nmfc": "182150", "description": "Toys / games, cartons", "freight_class": "125", "category": "Retail & Consumer"},
    {"nmfc": "168780", "description": "Sporting goods, NOI", "freight_class": "100", "category": "Retail & Consumer"},
    {"nmfc": "27700", "description": "Bicycles, cartons (KD)", "freight_class": "150", "category": "Retail & Consumer"},
    {"nmfc": "48500", "description": "Cosmetics / personal care, cases", "freight_class": "85", "category": "Retail & Consumer"},
    {"nmfc": "24120", "description": "Books / printed matter, cartons", "freight_class": "55", "category": "Retail & Consumer"},
    {"nmfc": "100240", "description": "Housewares / kitchenware, cartons", "freight_class": "100", "category": "Retail & Consumer"},
    {"nmfc": "133600", "description": "Lawn mowers / outdoor power equipment", "freight_class": "92.5", "category": "Retail & Consumer"},
    {"nmfc": "87700", "description": "Grills, BBQ, cartons", "freight_class": "125", "category": "Retail & Consumer"},
    {"nmfc": "119300", "description": "Luggage / bags, cartons", "freight_class": "150", "category": "Retail & Consumer"},
    {"nmfc": "154700", "description": "Pet supplies, NOI", "freight_class": "100", "category": "Retail & Consumer"},
]
