"""routes.tenant_pdfs — per-tenant branded Rate Confirmation + Invoice PDFs."""
import base64
import io
from datetime import datetime, timezone
from typing import Any, Dict, Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen.canvas import Canvas

W, H = letter


def _hex(c: str, fallback: str = "#F59E0B"):
    try:
        return colors.HexColor(c or fallback)
    except Exception:
        return colors.HexColor(fallback)


def _header(c: Canvas, brand: Dict[str, Any], title: str, doc_no: str):
    primary = _hex(brand.get("primary_color"))
    c.setFillColor(colors.HexColor("#0D1117"))
    c.rect(0, H - 110, W, 110, fill=1, stroke=0)
    c.setFillColor(primary)
    c.rect(0, H - 116, W, 6, fill=1, stroke=0)
    x = 46
    logo = brand.get("logo_b64")
    if logo:
        try:
            raw = base64.b64decode(logo.split(",")[-1])
            img = ImageReader(io.BytesIO(raw))
            c.drawImage(img, 46, H - 96, width=64, height=64, preserveAspectRatio=True, mask="auto")
            x = 122
        except Exception:
            pass
    c.setFont("Helvetica-Bold", 22)
    c.setFillColor(colors.white)
    c.drawString(x, H - 58, brand.get("company_name") or "Hot Shot TMS")
    c.setFont("Helvetica", 9)
    c.setFillColor(colors.HexColor("#9CA3AF"))
    c.drawString(x, H - 76, brand.get("tagline") or "Powered by Hot Shot TMS")
    c.setFont("Helvetica-Bold", 13)
    c.setFillColor(primary)
    c.drawRightString(W - 46, H - 58, title)
    c.setFont("Helvetica", 9)
    c.setFillColor(colors.white)
    c.drawRightString(W - 46, H - 74, doc_no)
    c.drawRightString(W - 46, H - 88, datetime.now(timezone.utc).strftime("%b %d, %Y"))


def _row(c: Canvas, y: float, label: str, value: str, primary):
    c.setFont("Helvetica-Bold", 9)
    c.setFillColor(primary)
    c.drawString(46, y, label.upper())
    c.setFont("Helvetica", 11)
    c.setFillColor(colors.HexColor("#1F2937"))
    c.drawString(180, y, value or "—")
    c.setStrokeColor(colors.HexColor("#E5E7EB"))
    c.line(46, y - 8, W - 46, y - 8)
    return y - 26


def _footer(c: Canvas, brand: Dict[str, Any]):
    c.setFillColor(colors.HexColor("#0D1117"))
    c.rect(0, 0, W, 46, fill=1, stroke=0)
    c.setFont("Helvetica", 8)
    c.setFillColor(colors.HexColor("#9CA3AF"))
    c.drawCentredString(W / 2, 18, f"{brand.get('company_name','')}  ·  generated by Hot Shot TMS  ·  {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")


def build_ratecon_pdf(brand: Dict[str, Any], load: Dict[str, Any]) -> bytes:
    buf = io.BytesIO()
    c = Canvas(buf, pagesize=letter)
    primary = _hex(brand.get("primary_color"))
    c.setTitle(f"Rate Confirmation {load['load_id']}")
    _header(c, brand, "RATE CONFIRMATION", load["load_id"])
    c.setFillColor(colors.HexColor("#FAFAF7"))
    c.rect(0, 46, W, H - 156, fill=1, stroke=0)
    y = H - 150
    y = _row(c, y, "Load ID", load["load_id"], primary)
    y = _row(c, y, "Origin", load.get("origin", ""), primary)
    y = _row(c, y, "Destination", load.get("destination", ""), primary)
    y = _row(c, y, "Pickup date", load.get("pickup_date", "") or "TBD", primary)
    y = _row(c, y, "Equipment", load.get("equipment", ""), primary)
    y = _row(c, y, "Carrier", load.get("carrier", "") or "TBD", primary)
    y = _row(c, y, "Carrier rate", f"${load.get('carrier_rate', 0):,.2f} (all-in, USD)", primary)
    y = _row(c, y, "Status", (load.get("status", "") or "").replace("_", " ").title(), primary)
    if load.get("notes"):
        y = _row(c, y, "Notes", str(load["notes"])[:90], primary)
    y -= 14
    c.setFont("Helvetica-Bold", 10)
    c.setFillColor(primary)
    c.drawString(46, y, "TERMS")
    c.setFont("Helvetica", 8.5)
    c.setFillColor(colors.HexColor("#475569"))
    for i, t in enumerate([
        "Carrier agrees to transport the above shipment at the stated all-in rate. Rate includes all fuel and accessorials unless noted.",
        "Signed POD required within 24 hours of delivery. Detention billed only with pre-approval.",
        "Double-brokering is strictly prohibited and voids this confirmation.",
    ]):
        c.drawString(46, y - 14 - i * 12, f"• {t}")
    y -= 68
    c.setStrokeColor(colors.HexColor("#94A3B8"))
    c.line(46, y, 250, y)
    c.line(320, y, W - 46, y)
    c.setFont("Helvetica", 8)
    c.drawString(46, y - 12, "Carrier signature / date")
    c.drawString(320, y - 12, f"{brand.get('company_name','')} — authorized signature")
    _footer(c, brand)
    c.save()
    return buf.getvalue()


def build_invoice_pdf(brand: Dict[str, Any], invoice: Dict[str, Any], load: Optional[Dict[str, Any]]) -> bytes:
    buf = io.BytesIO()
    c = Canvas(buf, pagesize=letter)
    primary = _hex(brand.get("primary_color"))
    c.setTitle(f"Invoice {invoice['invoice_id']}")
    _header(c, brand, "FREIGHT INVOICE", invoice["invoice_id"])
    c.setFillColor(colors.HexColor("#FAFAF7"))
    c.rect(0, 46, W, H - 156, fill=1, stroke=0)
    y = H - 150
    y = _row(c, y, "Invoice", invoice["invoice_id"], primary)
    y = _row(c, y, "Bill to", invoice.get("customer", "") or "Customer", primary)
    y = _row(c, y, "Load", invoice.get("load_id", ""), primary)
    if load:
        y = _row(c, y, "Lane", f"{load.get('origin','')} → {load.get('destination','')}", primary)
        y = _row(c, y, "Equipment", load.get("equipment", ""), primary)
        y = _row(c, y, "Delivered", load.get("pickup_date", "") or "—", primary)
    y = _row(c, y, "Status", (invoice.get("status", "") or "open").upper(), primary)
    y = _row(c, y, "Issued", (invoice.get("created_at", "") or "")[:10], primary)
    y -= 8
    c.setFillColor(colors.HexColor("#0D1117"))
    c.roundRect(46, y - 64, W - 92, 58, 8, fill=1, stroke=0)
    c.setFont("Helvetica-Bold", 10)
    c.setFillColor(colors.HexColor("#9CA3AF"))
    c.drawString(62, y - 28, "AMOUNT DUE (USD)")
    c.setFont("Helvetica-Bold", 26)
    c.setFillColor(primary)
    c.drawRightString(W - 62, y - 40, f"${invoice.get('amount', 0):,.2f}")
    c.setFont("Helvetica", 8.5)
    c.setFillColor(colors.HexColor("#475569"))
    c.drawString(46, y - 84, "Terms: Net 30 from invoice date. Please reference the invoice number on remittance.")
    _footer(c, brand)
    c.save()
    return buf.getvalue()
