"""
Slide content for the Tennant TMS user manual.
Shared between the React in-app deck and the .pptx export endpoint.
"""

SLIDES = [
    {
        "kind": "cover",
        "eyebrow": "Tennant Companies · Transportation Management System",
        "title": "User Manual · v1.5",
        "subtitle": "Mission-control TMS · now with Vault, Claims, Arcade, Themes, Trade Compliance & more",
        "footnote": "Prepared for the Tennant Transportation Team · Kirk Juergins",
    },
    {
        "kind": "toc",
        "title": "What's Inside",
        "sections": [
            "1. Getting Started — Login, Sidebar, Roles",
            "2. Command Center — Live Dashboard + Quotes Ticker",
            "3. Workbook — Renameable Tabs & Excel Export",
            "4. Shipments & Booking — Edit, Cancel, Customize Columns",
            "5. Live Tracking — Map & Containers",
            "6. Driver Tools — Console & Mobile Check-in",
            "7. Freight Audit & Pay — Approve, Pay, Dispute",
            "8. Carrier Onboarding — Vet, Approve, Send Packet",
            "9. Documents & Document Vault — BOL, CI, COI, MSDS",
            "10. Trade Compliance — Tariff, FTAs, Section 301, Sanctions",
            "11. Supplier Sourcing — Risk, Spend, Single-Source",
            "12. Machine Catalog — All 17 Current Tennant Models",
            "13. Payments & Claims — File, Reconcile, Recover",
            "14. Carrier Invites & Portal — Scoped Access",
            "15. KPI Reports — Download PDF/Excel, Email",
            "16. SAP S/4HANA Integration — Pull from Delivery",
            "17. Arcade — Connect 4, Tournaments, Trophies",
            "18. Themes — 7 Work-Friendly Visual Modes",
            "19. HUDLINK AI Co-Pilot & Webex",
            "20. Admin · Users & Roles",
        ],
    },
    {
        "kind": "section",
        "title": "1 · Getting Started",
        "tagline": "Sign in, learn the sidebar, understand your role.",
    },
    {
        "kind": "feature",
        "title": "Logging In",
        "subtitle": "Single sign-on via Google",
        "steps": [
            "Open the TMS — you land on the secure login page.",
            "Click 'Continue with Google' (Tennant-managed accounts only).",
            "First user to sign in automatically becomes Admin.",
            "Sessions last 7 days; expired sessions return you to the login screen.",
        ],
        "tips": ["Sessions are encrypted and stored as httpOnly cookies — no passwords are kept in the app."],
        "page_url": "/login",
    },
    {
        "kind": "feature",
        "title": "Sidebar Navigation",
        "subtitle": "Every module, one click away",
        "steps": [
            "The sidebar shows only the modules your role can access.",
            "Your user card sits at the bottom — name, role badge, and logout.",
            "Active page is highlighted with a cyan left-edge bar.",
            "Roles: ADMIN > AUDITOR > DISPATCHER > DRIVER (driver uses mobile only).",
        ],
        "tips": ["Admins see Integrations and Admin · Users. Auditors get Freight Audit & Pay. Dispatchers get Book Load, SAP Sync, Driver Console."],
    },
    {
        "kind": "section",
        "title": "2 · Command Center",
        "tagline": "Your mission-control dashboard.",
    },
    {
        "kind": "feature",
        "title": "Command Center · The Dashboard",
        "subtitle": "One glass for every mode of transit",
        "steps": [
            "Live map plots every active shipment (TL, LTL, parcel, ocean, air, rail) with pulsing cyan markers.",
            "7 KPI tiles up top: Active, Delayed, Delivered, Pending, On-Time %, Weight in Motion, Total Value.",
            "Right column: real-time weather for Golden Valley, Holland, Louisville; traffic alerts; mode mix donut.",
            "Bottom: 14-day volume trend chart and a 'Recent Manifest' table.",
            "Top of page: scrolling industry news ticker (FreightWaves, JOC, FMCSA, etc).",
        ],
        "tips": ["Click 'VIEW ALL →' on the manifest to jump straight to the full Shipments page."],
        "page_url": "/dashboard",
    },
    {
        "kind": "section",
        "title": "3 · Workbook",
        "tagline": "Your legacy Excel tracker — now live and shareable.",
    },
    {
        "kind": "feature",
        "title": "Workbook · Renameable Tabs",
        "subtitle": "Drop-in replacement for the legacy XLSX",
        "steps": [
            "13 default tabs ship pre-configured: Outbound TL, Outbound LTL, Expedites, Crate Spots, Seafreight 25M, 25 Import, 25 Quotes, Plant Hubs, IN Primary Carrier, IN Supplier Contacts, IN Carrier Contacts, Info, Volume Overview.",
            "Double-click any tab to rename it inline. Hit Enter to save, Escape to cancel.",
            "Click 'ADD TAB' to create a new tab; choose a Tab Type to pre-load columns.",
            "Hover the active tab to reveal Rename and Delete pill buttons.",
            "Use the search box to filter rows inside the current tab.",
        ],
        "tips": ["Tabs are saved per-tenant — every dispatcher sees the same tabs and renames. No more shared OneDrive XLSX confusion."],
        "page_url": "/workbook",
    },
    {
        "kind": "feature",
        "title": "Workbook · Excel Export",
        "subtitle": "One-click .xlsx download",
        "steps": [
            "'EXPORT THIS TAB' — generates a single-sheet .xlsx of just the active tab, with Tennant-branded header styling.",
            "'EXPORT ALL → XLSX' (top right) — generates a full workbook with one sheet per tab.",
            "Files download as Tennant_TMS_{TabName}.xlsx or Tennant_TMS_Workbook.xlsx.",
            "Header row freezes; columns auto-sized; Tennant cyan accents preserved.",
        ],
        "tips": ["Use 'EXPORT ALL' on Monday mornings to email a snapshot to the team or attach to your dispatch report."],
    },
    {
        "kind": "section",
        "title": "4 · Shipments & Booking",
        "tagline": "Find any load, book a new one.",
    },
    {
        "kind": "feature",
        "title": "Shipments · Carrier Toggle",
        "subtitle": "Quickly switch between carrier views",
        "steps": [
            "Top of page: 'CARRIER TOGGLE' — horizontal pill row with every carrier in your data plus an ALL pill.",
            "Click a carrier pill to filter the table to just that carrier's loads.",
            "Each pill shows a count, e.g., 'XPO LOGISTICS (7)'.",
            "Combine with the Mode filter (TL/LTL/Parcel/Ocean/Air/Rail) and Status filter (in_transit/delayed/delivered/pending).",
            "Search bar matches reference number, commodity, or destination.",
        ],
        "tips": ["Use the carrier toggle when escalating: filter to 'XPO Logistics', see all in-transit loads, then jump to Chat or Webex to ping the rep."],
        "page_url": "/shipments",
    },
    {
        "kind": "feature",
        "title": "Book Load",
        "subtitle": "Create a new shipment in under a minute",
        "steps": [
            "Choose Mode (TL/LTL/Parcel/Ocean/Air/Rail) — the Carrier dropdown auto-filters to that mode's approved carriers.",
            "Pick an Origin Facility (Golden Valley / Holland / Louisville).",
            "Enter Destination City and lat/lng (use Google Maps to grab coords if needed).",
            "Set pickup date, weight, pieces, commodity, and cargo value.",
            "Click 'BOOK LOAD →'. A shipment record is created with auto-generated BOL #, PRO #, container # (Ocean), and ETA.",
        ],
        "tips": ["Leave Reference blank to auto-generate a TN-##### reference."],
        "page_url": "/book-load",
    },
    {
        "kind": "section",
        "title": "5 · Live Tracking",
        "tagline": "Map view + ocean container search.",
    },
    {
        "kind": "feature",
        "title": "Live Tracking",
        "subtitle": "Real-time positions with progress bars",
        "steps": [
            "Full-screen Leaflet map with every shipment plotted at its current GPS coordinate.",
            "Right rail: Container Search — type a container #, BOL, or reference to filter the map.",
            "Each ocean container card shows progress 0–100%, ETA, and origin → destination.",
            "Click a marker on the map to see a detail popup with carrier, status, ETA, container #.",
            "Routes are drawn as dashed polylines from origin → current location → destination.",
        ],
        "tips": ["Driver mobile check-ins automatically update marker positions and the progress bar."],
        "page_url": "/tracking",
    },
    {
        "kind": "section",
        "title": "6 · Driver Tools",
        "tagline": "Mobile-first check-ins from the cab.",
    },
    {
        "kind": "feature",
        "title": "Driver Console (Office)",
        "subtitle": "Share mobile links · monitor check-ins",
        "steps": [
            "'Share Driver Links' grid — click COPY MOBILE LINK on any active load to copy a URL like /driver/SHP-XXXX.",
            "Text or email the link to the driver — no app install, no login required.",
            "Live Stream table auto-refreshes every 10 seconds with new check-ins.",
            "See driver name, phone, status, GPS coords, fuel %, odometer, and free-form notes.",
        ],
        "tips": ["You can also paste the driver link into a Webex space message — drivers receive it instantly."],
        "page_url": "/driver-console",
    },
    {
        "kind": "feature",
        "title": "Driver Mobile Page",
        "subtitle": "What the driver sees on their phone",
        "steps": [
            "Driver opens /driver/SHP-XXXX (the shared link) — load ticket displays: pickup, delivery, carrier, BOL, ETA.",
            "Driver enters name + phone once; it persists in their browser.",
            "Tap a status: Arriving Pickup, Loaded, En Route, Fuel Stop, Rest, Delayed, Arriving Destination, Delivered.",
            "Tap 'Capture GPS' to attach location. Optional: odometer, fuel %, note.",
            "Tap 'TRANSMIT CHECK-IN →'. Dispatch sees it within seconds.",
        ],
        "tips": ["The page is fully responsive — works on iOS Safari, Android Chrome, no installation."],
        "page_url": "/driver/SHP-XXXXXXXX",
    },
    {
        "kind": "section",
        "title": "7 · Freight Audit & Pay",
        "tagline": "Catch overcharges. Pay carriers in clicks.",
    },
    {
        "kind": "feature",
        "title": "Freight Audit & Pay",
        "subtitle": "Auditor & admin only",
        "steps": [
            "Top tiles: Total Billed, Paid, Pending, Disputed, and Overcharges Detected (audit savings).",
            "Carrier Toggle — same pill UI as Shipments to focus on one carrier's invoices.",
            "Table shows base charge, fuel, accessorials (with code tooltip), total, quoted total, and variance (red = overcharge).",
            "Per-row actions: APPROVE (pending → approved), PAY (approved → paid), DISPUTE (opens a reason dialog).",
            "Status filter pills: pending / approved / audit / disputed / paid.",
        ],
        "tips": ["The Variance column flags overcharges automatically. Sort by Variance desc to find the biggest audit savings."],
        "page_url": "/freight-pay",
    },
    {
        "kind": "section",
        "title": "8 · Carrier Onboarding",
        "tagline": "Vet, qualify, approve.",
    },
    {
        "kind": "feature",
        "title": "Carrier Onboarding & Vetting",
        "subtitle": "Decisions are admin-only",
        "steps": [
            "Top tiles show pipeline counts: In Review, Approved, Rejected, Total.",
            "Click 'NEW CARRIER' to open the vetting form — capture MC#, DOT#, SCAC, mode, contact, insurance amount + expiry, safety rating, CSA score.",
            "Each carrier row tracks 3 docs: W-9, COI (insurance certificate), Contract Signed — click the icon to toggle each.",
            "CSA score auto-colors: green <50, yellow 50-65, red >65.",
            "Insurance expiry shown with ⚠ flag if past due.",
            "Admin clicks APPROVE or REJECT to finalize.",
        ],
        "tips": ["Always confirm Insurance Expiry is at least 60 days out before approval."],
        "page_url": "/carrier-onboarding",
    },
    {
        "kind": "section",
        "title": "9 · Documents",
        "tagline": "BOL, CI, Packing, Weight, COO — generate and download as PDF.",
    },
    {
        "kind": "feature",
        "title": "Documents",
        "subtitle": "Five Tennant-branded PDFs",
        "steps": [
            "Top row: 5 document-type cards — Bill of Lading, Commercial Invoice, Packing Slip, Weight Certificate, Certificate of Origin.",
            "Click any card to open the Generate dialog. Pre-fills shipper as Tennant Company.",
            "Fill shipment ref, consignee, origin, destination, carrier, commodity, pieces, weight, value.",
            "For COO: also enter Country of Origin (defaults to USA).",
            "Click 'Generate Document' — record is created and a toast offers 'Download PDF →'.",
            "Archive table shows every generated doc; click the PDF button on any row to re-download.",
        ],
        "tips": ["PDFs are rendered with ReportLab — Tennant logo, cyan accents, signature block, and a footer timestamp."],
        "page_url": "/documents",
    },
    {
        "kind": "section",
        "title": "10 · Reference Tools",
        "tagline": "HS codes and trailer specs at your fingertips.",
    },
    {
        "kind": "feature",
        "title": "HS Code Lookup",
        "subtitle": "Tennant-relevant HTS codes",
        "steps": [
            "Search bar matches code prefix (e.g., '8479') or any keyword (e.g., 'scrubber', 'battery', 'motor').",
            "Results show: code, description, category, and duty %.",
            "18 pre-loaded codes covering scrubbers, vacuums, motors, batteries, brushes, plastic tanks, steel frames, wiring.",
            "Use these on the Commercial Invoice — they're the codes Customs expects from Tennant products.",
        ],
        "tips": ["For codes not in our list, click the link to the official US ITC HTS lookup."],
        "page_url": "/hs-lookup",
    },
    {
        "kind": "feature",
        "title": "Trailer Specs",
        "subtitle": "Proportional visual + capacity charts",
        "steps": [
            "Top section: each of 8 trailer types drawn as a proportional bar showing actual length, with dimensions and 'best for' use cases.",
            "Bottom-left chart: pallet capacity (40x48' positions) across all trailers.",
            "Bottom-right chart: max payload in lbs across all trailers.",
            "Reference for: 53' DV, 48' DV, 28' Pup, 53' Reefer, 48' Flatbed, 20' Container, 40' Container, 40' High Cube.",
        ],
        "tips": ["Use when matching a load to equipment — e.g., need 20+ pallets and weight-sensitive? Go 53' Dry Van."],
        "page_url": "/trailers",
    },
    {
        "kind": "section",
        "title": "11 · Integrations",
        "tagline": "Every system Tennant runs — connected.",
    },
    {
        "kind": "feature",
        "title": "Integrations Hub",
        "subtitle": "Admin-only overview",
        "steps": [
            "Grouped by category: ERP, Productivity, Analytics, Communication, TMS, Parcel, LTL, Ocean/Air.",
            "Each card shows status (CONNECTED / DEGRADED / OFFLINE), endpoint host, and last-sync time.",
            "Currently connected: SAP S/4HANA, SharePoint, PowerBI, Outlook, Logix, UPS, FedEx, DHL, ArcBest, Fastfrate, R&L, XPO, SAIA, Kuehne+Nagel, Cisco Webex.",
            "Click 'Configure' on any card to open the integration settings (production: opens credential management).",
        ],
        "tips": ["A red OFFLINE badge typically means OAuth expired — refresh the integration to re-authenticate."],
        "page_url": "/integrations",
    },
    {
        "kind": "feature",
        "title": "SAP S/4HANA Sync",
        "subtitle": "OData connector for SO and PO",
        "steps": [
            "Connection panel shows host, OData service path, client (100), service account, and OAuth method.",
            "Tabs: Sales Orders, Purchase Orders, Imports Only (auto-filtered), Sync Logs.",
            "Sales Orders pull from API_SALES_ORDER_SRV — see SO#, customer, material, quantity, plant, requested delivery date, status, Incoterms.",
            "Purchase Orders pull from API_PURCHASEORDER_PROCESS_SRV — supplier, component, quantity, plant, delivery, IsImport flag.",
            "Click 'TRIGGER SYNC' to pull fresh data; a log row records duration, counts, and status.",
            "Plant codes: 1010 Golden Valley · 1020 Holland · 1030 Louisville.",
        ],
        "tips": ["Imports Only tab is the fastest way to see all inbound K+N containers awaiting drayage."],
        "page_url": "/sap-sync",
    },
    {
        "kind": "section",
        "title": "12 · Cisco Webex",
        "tagline": "Post to spaces. Schedule meetings.",
    },
    {
        "kind": "feature",
        "title": "Cisco Webex",
        "subtitle": "Logistics-native collaboration",
        "steps": [
            "Connection panel shows org ID, bot email, granted scopes, and status.",
            "Tabs: Spaces (7 default groups), Meetings (upcoming), Activity Log.",
            "Each space card lists members and last activity; click 'Post' to send a message — optionally tag a shipment reference.",
            "Schedule a meeting via the 'Schedule Meeting' button: title, start, duration, invitees.",
            "Each meeting card has a JOIN button that opens the Webex meeting URL.",
        ],
        "tips": ["The 'Kirk Juergins — Direct Messages' space is pre-wired for quick 1:1 escalations to the director."],
        "page_url": "/webex",
    },
    {
        "kind": "section",
        "title": "13 · HUDLINK AI Co-Pilot",
        "tagline": "Claude Sonnet 4.5, trained on Tennant ops.",
    },
    {
        "kind": "feature",
        "title": "HUDLINK AI",
        "subtitle": "Ask anything about transportation, freight, customs",
        "steps": [
            "Click an opening suggestion or type your own question in the input box.",
            "HUDLINK understands Tennant context: 3 plants, K+N imports, HS chapter 8479/8508/8507, Incoterms 2020, your carriers.",
            "Use it for: HS code recommendations, Incoterms selection, accessorial dispute rules, carrier comparison, document checklists.",
            "Conversation history persists across sessions — click 'Clear' to start fresh.",
            "Style is terse and action-oriented — bullets, codes, and clear primary recommendations.",
        ],
        "tips": ["Example prompts: 'Compare XPO vs SAIA for Holland→Atlanta LTL', 'HS code for a T16 AMR?', 'Auto-disputable accessorials?'"],
        "page_url": "/ai-assistant",
    },
    {
        "kind": "section",
        "title": "14 · KPI Reports & Team Chat",
        "tagline": "Measure performance, communicate in real time.",
    },
    {
        "kind": "feature",
        "title": "KPI Reports",
        "subtitle": "Performance analytics for the whole team",
        "steps": [
            "Top: Total Shipments, On-Time Rate, Total Weight, Total Value.",
            "14-day cost trend line chart for spend analytics.",
            "Carrier Scorecard — horizontal bar chart of on-time % by carrier (sorted).",
            "Radar chart: Score vs Volume profile by carrier.",
            "Bottom table: detailed scorecard with total / delivered / delayed / on-time % per carrier.",
        ],
        "tips": ["Pull this view in your monthly review — it tells the carrier story without a PowerPoint."],
        "page_url": "/reports",
    },
    {
        "kind": "feature",
        "title": "Team Chat",
        "subtitle": "Real-time WebSocket messaging",
        "steps": [
            "7 default channels: general, ops-dispatch, import-export, carrier-issues, louisville, holland, golden-valley.",
            "Left rail: channel list with descriptions; click any to switch.",
            "Type a message and hit Send (or Enter). It appears instantly for every connected user.",
            "Messages persist in MongoDB; history loads on channel switch.",
            "Avatars derive from your Google profile picture.",
        ],
        "tips": ["Use plant-specific channels (louisville, holland, golden-valley) for facility-only coordination."],
        "page_url": "/chat",
    },
    {
        "kind": "section",
        "title": "15 · Admin & Quick Links",
        "tagline": "User management and outside resources.",
    },
    {
        "kind": "feature",
        "title": "Admin · Users & Roles",
        "subtitle": "Admin-only RBAC",
        "steps": [
            "Top tiles: role counts (admins, auditors, dispatchers, drivers).",
            "Table lists every user with current role and a role-change dropdown.",
            "Cannot demote the only remaining admin (server enforces).",
            "Click 'SEED TEAM' to add 5 sample team members for demo/training.",
            "Bottom: RBAC Reference cards explaining each role's capabilities.",
        ],
        "tips": ["For a 250-user rollout, assign roles thoughtfully: most users = dispatcher; finance team = auditor; 2-3 leaders = admin."],
        "page_url": "/admin/users",
    },
    {
        "kind": "feature",
        "title": "Quick Links",
        "subtitle": "Direct links to outside resources",
        "steps": [
            "Grouped by category: Import/Export, DOT, Tariff, Ports, Weather, Air.",
            "Includes: ACE Portal (CBP), FMCSA SAFER, USDOT, CBP Trade, USTR HTS, Census Schedule B, major ports, FAA NOTAMs.",
            "All open in new tabs.",
        ],
        "tips": ["Bookmark this page for quick access during customs filings."],
        "page_url": "/links",
    },
    {
        "kind": "section",
        "title": "Part II · 2026 Update",
        "tagline": "New modules added in the v1.5 release",
    },
    {
        "kind": "feature",
        "title": "Shipments — Edit, Cancel, Customize",
        "subtitle": "Shipments tab · v1.5",
        "steps": [
            "Click the pencil icon on any row to open the Edit Shipment modal — every field is editable.",
            "Quick-status dropdown lets you change pending → at_origin → in_transit → delivered without opening the modal.",
            "Click the red X to soft-cancel a shipment. Records are preserved and recoverable.",
            "Toggle 'Show Cancelled' to view archived shipments in the same table.",
            "Click 'Columns (12/18)' button (top-right of table) to toggle visibility and drag-resize widths.",
            "Column preferences are saved per browser to localStorage.",
        ],
        "tips": [
            "Soft-delete preserves audit trail. Use it instead of deleting permanently.",
            "Resize columns by dragging their right edge in the header.",
        ],
        "page_url": "/shipments",
    },
    {
        "kind": "feature",
        "title": "Shipments — Email Routing Guide & Carrier",
        "subtitle": "Shipments tab · v1.5",
        "steps": [
            "Green Mail icon: composes a routing guide for the customer with BOL/PRO/ETA/accessorial details.",
            "Yellow Mail icon: composes a carrier email — choose a template (ETA, POD, Exception Inquiry, Rate Confirmation).",
            "Each email opens a modal with the full body, a Copy button, and an 'Open in Mail Client' (mailto:) launcher.",
            "Set customer_contact_email and carrier_contact_email in the Edit modal so 'To:' is auto-filled.",
        ],
        "tips": [
            "All emails are mailto-mocked — they open in your default mail client (Outlook, Gmail web, etc.) ready to send.",
        ],
        "page_url": "/shipments",
    },
    {
        "kind": "feature",
        "title": "Shipments — Carrier BOL Storage",
        "subtitle": "Shipments tab · v1.5",
        "steps": [
            "Upload icon on a row → upload a signed BOL PDF/image (stored in MongoDB GridFS).",
            "Once stored, the icon turns into a Download icon — click to retrieve the file.",
            "Carrier portal users can upload BOLs for their own loads from the same control.",
        ],
        "tips": ["PDFs preferred; images accepted for mobile-snapped PODs."],
        "page_url": "/shipments",
    },
    {
        "kind": "feature",
        "title": "Book Load — Pull from SAP S/4HANA",
        "subtitle": "Book Load tab · v1.5",
        "steps": [
            "Click 'Pull from SAP →' to open a picker of open Deliveries (SO #, customer, material, qty, plant).",
            "Selecting a row auto-fills Reference, SAP Delivery #, Commodity, Pieces, Pallet Count.",
            "Add Length / Width / Height per pallet — density (lb/ft³) calculates live; freight class suggestion appears if NMFC class mismatches the density formula.",
            "Pick NMFC code from the Tennant-curated list — selecting one auto-sets the freight class.",
            "Toggle Accessorials (Liftgate, Residential, Inside Delivery, Hazmat Handling, …) — chosen ones save with the booking.",
            "Fill optional Customer & Carrier contact emails so future routing/carrier emails auto-populate the To: field.",
        ],
        "tips": [
            "Density formula: lbs ÷ (L×W×H / 1728 × pallets). Tennant scrubbers usually land in class 85.",
            "Hazmat Class 9 batteries: select 'Hazmat Handling' accessorial and document UFLPA diligence in Trade Compliance.",
        ],
        "page_url": "/book-load",
    },
    {
        "kind": "feature",
        "title": "KPI Weekly Weights",
        "subtitle": "Reports tab",
        "steps": [
            "Reports → bottom section shows 12-week trailing avg shipped weight per facility (GVM / HOM / LVK).",
            "Three tiles show current week avg, 12-wk avg, and WoW delta per facility.",
            "Use to spot demand shifts between sites and seasonal anomalies.",
        ],
        "page_url": "/reports",
    },
    {
        "kind": "feature",
        "title": "KPI Reports — Download & Email",
        "subtitle": "Reports tab · v1.5",
        "steps": [
            "Reports → 'Generate Report' bar at the top.",
            "Download PDF or Excel — instantly streams a Tennant-branded multi-section report.",
            "Click 'Email Report' to compose a recipient-ready email with all headline KPIs in the body.",
            "Modal shows full subject + body. Copy or 'Open in Mail Client' to send via Outlook / Gmail / etc.",
            "Audit log records every report generation and email request.",
        ],
        "page_url": "/reports",
    },
    {
        "kind": "feature",
        "title": "Document Vault",
        "subtitle": "v1.5 · GridFS-backed storage",
        "steps": [
            "Stores Insurance COIs, W-9s, Carrier Agreements, MSDS/SDS, Onboarding Packets, Tariffs, Quotes, Bids, etc.",
            "Click 'Upload File' → pick file, choose category, link to a carrier/vendor/shipment, set expiry date.",
            "Filter by category, search by filename/notes/related entity.",
            "Files with expiry < 60 days display in yellow; expired files show red AlertTriangle icon.",
            "Click any file row to download. Admin-only: delete.",
        ],
        "tips": [
            "Tag every COI with the carrier name in 'Related To' for instant filtering.",
            "Expiry tracking auto-surfaces compliance gaps.",
        ],
        "page_url": "/vault",
    },
    {
        "kind": "feature",
        "title": "Freight Payments & Claims",
        "subtitle": "v1.5",
        "steps": [
            "Top tiles: Total Claims, Open / Filed, Settled, Total Claimed $, Recovered $ (with recovery rate %).",
            "Filter by status (open / filed / acknowledged / settled / partial / denied).",
            "Click 'New Claim' to file: link to a shipment, choose type (damage/shortage/loss/overage/freight_overcharge), amount, description.",
            "Manage button → update status, log amount recovered, add notes.",
        ],
        "tips": ["File freight_overcharge claims when accessorials were billed but not authorized."],
        "page_url": "/claims",
    },
    {
        "kind": "feature",
        "title": "Carrier Invites (Admin)",
        "subtitle": "v1.5 · Scoped portal access",
        "steps": [
            "Admin-only tab. Click 'New Invite' → fill carrier company name, invitee email, expiry days (default 14).",
            "On submit you receive a tokenized invite link AND a ready-made email body.",
            "Click 'Open in Mail Client' or copy-and-paste into your usual mail tool.",
            "Recipients land on /accept-invite — they enter name + email and gain a 'carrier' session for 7 days.",
            "Carriers see ONLY shipments where carrier = their company. Everything else is hidden.",
            "Revoke any pending invite at any time.",
        ],
        "tips": [
            "For shared dispatch desks, send the invite to a team alias rather than a single person.",
            "Carriers can upload BOLs for their loads — no admin help required.",
        ],
        "page_url": "/carrier-invites",
    },
    {
        "kind": "feature",
        "title": "Carrier Onboarding · Send Packet",
        "subtitle": "v1.5",
        "steps": [
            "On the Carrier Onboarding tab each row has three buttons: PACKET, APPROVE, REJECT.",
            "PACKET composes a complete Tennant onboarding requirements packet email — Master Agreement, COI minimums, W-9, SCAC/MC/DOT, CSA scorecard, EDI 204/214/210 confirmation, lane matrix.",
            "Modal shows subject + body. Copy or 'Open in Mail Client'. Audit log records the send.",
        ],
        "page_url": "/carrier-onboarding",
    },
    {
        "kind": "feature",
        "title": "Trade Compliance",
        "subtitle": "v1.5 · Tariff + sanctions",
        "steps": [
            "11 sections: Snapshot, Tariff Schedules (18 HTS codes Tennant uses), Trade Programs (USMCA / KORUS / FTZ / Drawback / GSP / §321), Section 301, Section 232, Country of Origin, Watchlists & Sanctions, Broker / ACE Filings, Key Regulations, Recent Alerts, Quick Links.",
            "Search HTS by keyword (e.g. 'lithium'). Section 301 list & rate show inline for each code.",
            "Watchlists tile shows last screen timestamp + 30d match count + embargoed-country chips.",
            "Alerts feed surfaces the latest USTR / CBP / FMCSA notices with severity badges.",
            "Quick Links open USITC HTS, ACE Portal, BIS Entity List, OFAC SDN, etc., in new tabs.",
        ],
        "tips": [
            "Use the Section 301 mitigation tile during sourcing decisions — Tennant strategy is to shift CoO to Korea (KORUS) and USMCA.",
        ],
        "page_url": "/trade-compliance",
    },
    {
        "kind": "feature",
        "title": "Supplier Sourcing",
        "subtitle": "v1.5",
        "steps": [
            "20 active suppliers tracked: battery, harness, engine, plastics, frames, motors, hydraulics, brushes, squeegees, electronics, tires.",
            "Top tiles: total suppliers, primary count, annual spend $, single-source count, high-risk count, contracts expiring in 12 months.",
            "Country spend bar chart for top 8 supply countries.",
            "Filter by category, country, primary-only, single-source-only.",
            "Each card shows lead time, MOQ, on-time %, quality PPM, risk score, annual spend, FTA eligibility, contract expiry, contact, alt sources.",
        ],
        "tips": [
            "Red-bordered cards (risk ≥25) need immediate dual-source action.",
            "Single-source toggle reveals every component without backup — supplier risk in one click.",
        ],
        "page_url": "/suppliers",
    },
    {
        "kind": "feature",
        "title": "Tennant Machine Catalog",
        "subtitle": "v1.5",
        "steps": [
            "17 current Tennant models: T16AMR, T7AMR, T681, T500, T350, T300, T2, S30, S20, S10, M30, M17, B7, B5, Green Machine, ATLV, EX-CAN-7.",
            "Filter by category (AMR, Rider Scrubber, Walk-Behind, Industrial Sweeper, Combo, Burnisher, Outdoor, Carpet).",
            "Each card: hero photo, model, category, runtime, power.",
            "Click any card to open the detail modal — full-color hero image, list price, power, deck width, runtime, weight, tank, highlighted features.",
        ],
        "tips": [
            "Drivers and carriers see this catalog too — useful for unloading equipment they may have never seen.",
        ],
        "page_url": "/machines",
    },
    {
        "kind": "feature",
        "title": "Arcade · Tournaments · Trophies",
        "subtitle": "v1.5 · Connect 4",
        "steps": [
            "Four tabs: Lobby, Challenges, Leaderboard, Tournaments.",
            "Click 'Challenge a Teammate' → pick any TMS user → optional trash-talk message → send.",
            "Recipient sees the challenge in their Inbox; Accept creates an active game.",
            "Click 'Open Lobby Game' to create an open seat anyone can fill from the lobby.",
            "Game board: 7 columns, click drop-arrow to play a piece. Server enforces turn order and detects winner.",
            "Leaderboard ranks players by trophies (🥇🥈🥉), then wins. Tiers: Rookie → Contender → Champion → Legend.",
            "Admin/Dispatcher: 'New Tournament' → pick 4/8/16 participants → bracket auto-generated. Round winners advance automatically. Champion earns +3 bonus trophies.",
        ],
        "tips": [
            "Tournaments are a great team-building lunch activity. Try the 4-player single elimination first.",
        ],
        "page_url": "/arcade",
    },
    {
        "kind": "feature",
        "title": "Inspirational Quotes Ticker",
        "subtitle": "Command Center",
        "steps": [
            "Subtle ticker at the top of Dashboard rotates 100 curated quotes every 12 seconds.",
            "Includes classics from Churchill, Drucker, Lombardi, Einstein, plus logistics-specific lines.",
            "Each user sees a randomized starting position so no two screens show the same quote at once.",
        ],
        "page_url": "/dashboard",
    },
    {
        "kind": "feature",
        "title": "Visual Theme Switcher",
        "subtitle": "Topbar · every page",
        "steps": [
            "Click the palette button in the Topbar to open the theme panel.",
            "Choose from 7 work-friendly themes: HUD Cyan (default), Forest Calm, Sunset Warm, Arctic, Lavender, Mocha, Solar Light.",
            "Theme applies instantly to every page and is saved per-browser.",
            "Solar Light is the only light theme — ideal for daylight working at warehouse offices.",
        ],
        "tips": [
            "Late-shift dispatchers tend to prefer Mocha or Sunset.",
            "Auditors with all-day spreadsheet work tend to prefer Forest Calm or Lavender.",
        ],
        "page_url": "anywhere · Topbar",
    },
    {
        "kind": "feature",
        "title": "SAP S/4HANA Quick Actions on Dashboard",
        "subtitle": "Command Center",
        "steps": [
            "Top of Command Center has a SAP S/4HANA action row with deep-links to Sales Orders, Purchase Orders, Imports, Open Deliveries, Materials, Sync Logs.",
            "Below: 'Top Part Numbers · Open Orders' widget showing live materials data with NMFC/class.",
            "Every part-number cell is a hyperlink to the SAP material record.",
        ],
        "page_url": "/dashboard",
    },
    {
        "kind": "closing",
        "title": "Questions?",
        "subtitle": "HUDLINK AI is built in — ask it anything.",
        "footnote": "Tennant Companies · TMS v1.5 · 2026 Update · Generated by Tennant Transportation Team",
    },
]
